### ISSUE TITLE
osl_maxfilter 'adjacent' output returns error

### ISSUE THREAD

**Issue by matsvanes** [OHBA-analysis/osl#26]
when using 'adjacent' as output directory for osl_maxfilter, i.e., files are supposed to be stored in the same directory as the input file, I get an error about the log file not being found (see below). Probably something is going wrong in the initialization of the log file(s). FYI I'm running the following in an active osl environment on the latest version of OSL
The code I'm running:
```
osl_maxfilter tmp.txt 'adjacent' --maxpath /neuro/bin/util/maxfilter --scanner Neo --tsss --mode multistage --headpos --movecomp
```

The message printed to screen:
```
['tmp.txt', 'adjacent', '--maxpath', '/neuro/bin/util/maxfilter', '--scanner', 'Neo', '--tsss', '--mode', 'multistage', '--headpos', '--movecomp']
Namespace(files='tmp.txt', outdir='adjacent', maxpath='/neuro/bin/util/maxfilter', mode='multistage', headpos=True, movecomp=True, movecompinter=False, autobad=False, autobad_dur=None, bad=None, badlimit=None, trans=None, origin=None, frame=None, force=False, tsss=True, st=10, corr=0.98, inorder=None, outorder=None, hpie=None, hpig=None, scanner='Neo', ctc=None, cal=None, overwrite=False, dryrun=False)


OHBA-Maxfilter


Processing 1 files
Outputs will be saved alongside inputs


Processing run 1/1 : /ohba/pi/knobre/datasets/cmore/rawbids/sub-005/meg/sub-005_task-CTET.fif
/neuro/bin/util/maxfilter -f /ohba/pi/knobre/datasets/cmore/rawbids/sub-005/meg/sub-005_task-CTET.fif -o /ohba/pi/knobre/datasets/cmore/rawbids/sub-005/meg/sub-005_task-CTET_autobad_sss.fif -autobad on -cal /net/aton/meg_pool/data/TriuxNeo/system/sss/sss_cal.dat -ctc /net/aton/meg_pool/data/TriuxNeo/system/ctc/ct_sparse.fif -v > >(tee -a /ohba/pi/knobre/datasets/cmore/rawbids/sub-005/meg/sub-005_task-CTET_autobad_sss_autobad.log) 2> >(tee -a /ohba/pi/knobre/datasets/cmore/rawbids/sub-005/meg/sub-005_task-CTET_autobad_sss_autobad_err.log >&2)


tee: /ohba/pi/knobre/datasets/cmore/rawbids/sub-005/meg/sub-005_task-CTET_autobad_sss_autobad_err.log: Permission denied
tee: /ohba/pi/knobre/datasets/cmore/rawbids/sub-005/meg/sub-005_task-CTET_autobad_sss_autobad.log: Permission denied
**************************************************
*** This is MaxFilter(TM) version 2.2.20       ***
*** Compilation date: Dec  3 2019 13:06:57     ***
*** Please report problems to support@megin.fi ***
**************************************************
No processing records found.
SSS origin (head) 0.0, 0.0, 40.0 mm.
Time scale: #f = 12.000 s, #l = 836.000 s 
Applying the fine-calibration in /net/aton/meg_pool/data/TriuxNeo/system/sss/sss_cal.dat.
Using the cross-talk matrix in /net/aton/meg_pool/data/TriuxNeo/system/ctc/ct_sparse.fif.
Opened FIFF file /ohba/pi/knobre/datasets/cmore/rawbids/sub-005/meg/sub-005_task-CTET.fif (824 data buffers).
EXIT 4: The output file already exists. Output file /ohba/pi/knobre/datasets/cmore/rawbids/sub-005/meg/sub-005_task-CTET_autobad_sss.fif was not written!
Failed to create file /ohba/pi/knobre/datasets/cmore/rawbids/sub-005/meg/sub-005_task-CTET_autobad_sss.fif for writing!
Traceback (most recent call last):
  File "/home/mvanes/anaconda3/envs/osl/bin/osl_maxfilter", line 8, in <module>
    sys.exit(main())
  File "/home/mvanes/anaconda3/envs/osl/lib/python3.9/site-packages/osl/maxfilter/maxfilter.py", line 615, in main
    run_multistage_maxfilter(infifs[idx], outbase, vars(args))
  File "/home/mvanes/anaconda3/envs/osl/lib/python3.9/site-packages/osl/maxfilter/maxfilter.py", line 332, in run_multistage_maxfilter
    with open(outlog, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/ohba/pi/knobre/datasets/cmore/rawbids/sub-005/meg/sub-005_task-CTET_autobad_sss_autobad.log'
```

**Comment by matsvanes** [comment]
Related to the above (but perhaps worthy of a new issue), it would be great if we have more flexibility of where to store output files. Often we want a specific folder for each subject (e.g. "sub-001"), but it is currently not possible to do this.
I thought of a few options to do exactly this:
- have a .txt file as input for the output directory, with each line specifying the output path to the corresponding line in the input paths text file
- I thought of supplying a (custom made) function as an argument which molds the input path into an output path (e.g. with operations like `inputpath.replace('rawdata', 'maxfiltered')`. However, as I understand it, it's not possible to give a function input argument to a command line call, and it is currently not possible to run osl_maxfilter from within let's say iPython (e.g. `osl.preprocessing.maxfilter()`)
- Any other way that is much more straightforward then what I thought of..

**Comment by cgohil8** [comment]
I just tested this on hbaws34, i couldn't reproduce the error. This might be setup/machine specific. Reopen this if it reoccurs.
